image:
  repository: ghcr.io/gkalian/amuzing-subs-calendar
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

podSecurityContext:
  enabled: true
  fsGroup: 1001
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  ingressClassName: ''
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: example-tls
      hosts:
        - example.com 

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  type: pvc
  size: 1Gi
  storageClass: ''
  accessModes:
    - ReadWriteOnce
  mountPath: /data
  hostPath:
    path: /srv/amuzing-subs-calendar/data
    type: DirectoryOrCreate
  
env:
  PORT: '8080'
  LOG_LEVEL: 'info'